INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 1, 'CAMION', 14040.000000000002);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 1, 'CAMION+CARRO', 28080.000000000004);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 1, 'CAMION', 8640.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 1, 'CAMION+CARRO', 17280.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 1, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 1, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 2, 'CAMION', 12960.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 2, 'CAMION+CARRO', 25920.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 2, 'CAMION', 7830.000000000001);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 2, 'CAMION+CARRO', 15660.000000000002);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 2, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 2, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 3, 'CAMION', 14040.000000000002);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 3, 'CAMION+CARRO', 28080.000000000004);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 3, 'CAMION', 8640.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 3, 'CAMION+CARRO', 17280.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 3, 'CAMION', 7020.000000000001);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 3, 'CAMION+CARRO', 14040.000000000002);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 4, 'CAMION', 12420.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 4, 'CAMION+CARRO', 24840.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 4, 'CAMION', 7020.000000000001);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 4, 'CAMION+CARRO', 14040.000000000002);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 4, 'CAMION', 4000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 4, 'CAMION+CARRO', 8000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 5, 'CAMION', 10800.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 5, 'CAMION+CARRO', 21600.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 5, 'CAMION', 5400.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 5, 'CAMION+CARRO', 10800.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 5, 'CAMION', 4000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 5, 'CAMION+CARRO', 8000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 6, 'CAMION', 13500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 6, 'CAMION+CARRO', 27000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 6, 'CAMION', 8100.000000000001);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 6, 'CAMION+CARRO', 16200.000000000002);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 6, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 6, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 7, 'CAMION', 9720.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 7, 'CAMION+CARRO', 19440.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 7, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 7, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 7, 'CAMION', 4000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 7, 'CAMION+CARRO', 8000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 8, 'CAMION', 11880.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 8, 'CAMION+CARRO', 23760.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 8, 'CAMION', 6480.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 8, 'CAMION+CARRO', 12960.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 8, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 8, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 9, 'CAMION', 10260.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 9, 'CAMION+CARRO', 20520.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 9, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 9, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 9, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 9, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 10, 'CAMION', 8100.000000000001);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 10, 'CAMION+CARRO', 16200.000000000002);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 10, 'CAMION', 4000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 10, 'CAMION+CARRO', 8000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 10, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 10, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 11, 'CAMION', 7560.000000000001);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 11, 'CAMION+CARRO', 15120.000000000002);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 11, 'CAMION', 4000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 11, 'CAMION+CARRO', 8000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 11, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 11, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 12, 'CAMION', 6750.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 12, 'CAMION+CARRO', 13500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 12, 'CAMION', 4000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 12, 'CAMION+CARRO', 8000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 12, 'CAMION', 5940.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL VALDIVIA', 12, 'CAMION+CARRO', 11880.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 13, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 13, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 13, 'CAMION', 4000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 13, 'CAMION+CARRO', 8000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 14, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 14, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 14, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 14, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 15, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 15, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 15, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 15, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 16, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 16, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 16, 'CAMION', 7020.000000000001);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 16, 'CAMION+CARRO', 14040.000000000002);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 17, 'CAMION', 4000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 17, 'CAMION+CARRO', 8000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 17, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL OSORNO', 17, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 18, 'CAMION', 4000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 18, 'CAMION+CARRO', 8000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 19, 'CAMION', 4000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 19, 'CAMION+CARRO', 8000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 20, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 20, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 21, 'CAMION', 4500.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 21, 'CAMION+CARRO', 9000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL CHILOE', 22, 'CAMION', 4000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL CHILOE', 22, 'CAMION+CARRO', 8000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 22, 'CAMION', 5940.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 22, 'CAMION+CARRO', 11880.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL CHILOE', 23, 'CAMION', 4000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL CHILOE', 23, 'CAMION+CARRO', 8000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 23, 'CAMION', 9180.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 23, 'CAMION+CARRO', 18360.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL CHILOE', 24, 'CAMION', 4000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL CHILOE', 24, 'CAMION+CARRO', 8000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 24, 'CAMION', 9990.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 24, 'CAMION+CARRO', 19980.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL CHILOE', 25, 'CAMION', 4000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL CHILOE', 25, 'CAMION+CARRO', 8000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 25, 'CAMION', 9450.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 25, 'CAMION+CARRO', 18900.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL CHILOE', 26, 'CAMION', 4000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL CHILOE', 26, 'CAMION+CARRO', 8000.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 26, 'CAMION', 10530.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 26, 'CAMION+CARRO', 21060.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL CHILOE', 27, 'CAMION', 8100.000000000001);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL CHILOE', 27, 'CAMION+CARRO', 16200.000000000002);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 27, 'CAMION', 12690.0);
INSERT INTO public.bonos_produccion (region, planta, tipo_vehiculo, valor) VALUES ('TRESOL PUERTO MONTT', 27, 'CAMION+CARRO', 25380.0);