INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ABARROTES ECONOMICOS LTDA ACUENTA ALERCE', 'PUERTO MONTT/ALERCE', '1 C.C.15M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ABARROTES ECONOMICOS LTDA ACUENTA FRUTILLAR', 'PUERTO MONTT', '1 C.C.15M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ABARROTES ECONOMICOS LTDA CASTRO', 'CHILOE', '1 C.C.15M³', 'ASIMILABLE', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ABARROTES ECONOMICOS LTDA MARIǪUINA', 'VALDIVIA', '1C.C. 15M³', 'ASIMILABLE', 'MORROMPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ABARROTES ECONOMICOS LTDA RIO BUENO', 'RIO BUENO', 'N/A RECOLECTOR', 'ASIMILABLE', 'MORROMPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ABARROTES ECONOMICOS LTDA TERMINAL VALDIVIA', 'VALDIVIA', 'N/A RECOLECTOR', 'ASIMILABLE', 'MORROMPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ABARROTES ECONOMICOS LTDA OSORNO', 'OSORNO', 'N/A RECOLECTOR', 'ASIMILABLE', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ACME CHILE SPA', 'PUERTO MONTT', '1 COMPACTADOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ACME CHILE SPA', 'PUERTO MONTT', '1 C.A. 20M³', 'ESCOMBROS', 'ESCOMBRERA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ADMIN DE SUPERMERCADOS HIPER LTDA. CARDONAL', 'PUERTO MONTT', '1 COMPACTADOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ADMIN DE SUPERMERCADOS HIPER LTDA. VALDIVIA', 'VALDIVIA', '1 COMPACTADOR', 'ASIMILABLE', 'MORROMPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ADMIN DE SUPERMERCADOS HIPER LTDA.OSORNO', 'OSORNO', '1 COMPACTADOR', 'ASIMILABLE', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ADMIN DE SUPERMERCADOS HIPER LTDA.PARǪUE INDUSTRIAL', 'PUERTO MONTT', '1 COMPACTADOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ADMINISTRADORA DE SUPERMERCADOS EXPRESS OSORNO', 'OSORNO', '1 COMPACTADOR', 'ASIMILABLE', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ADMINISTRADORA DE SUPERMERCADOS EXPRESS PTO VARAS', 'PUERTO MONTT', '1 COMPACTADOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ADMINISTRADORA DE SUPERMERCADOS EXPRESS VALDIVIA', 'VALDIVIA', '1 COMPACTADOR', 'ASIMILABLE', 'MORROMPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ADMINISTRADORA DE SUPERMERCADOS EXPRESS PANGUIPULLI', 'PANGUIPULLI', '1 COMPACTADOR', 'ASIMILABLE', 'MORROMPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ADMINISTRADORA DE VENTAS AL DETALLE LTDA TRAGUN ORIENTE Y TRAFUN P', 'OSORNO', 'N/A-RECOLECTOR', 'ASIMILABLE', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ADMINISTRADORA DE VENTAS AL DETALLE LTDA PTO VARAS, PTO MONTT', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ADMINISTRADORA DE VENTAS AL DETALLE LTDA PARGUA', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('AGUAS DECIMA S.A.', 'VALDIVIA', '3 COMPACTADORES DE LODO', 'LODOS', 'PREDIO SAN JAVIER');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('AKVA GROUP CHILE S.A.', 'PUERTO MONTT', '3 C.A. 20M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ALGAS MARINAS S.A. (MIDESA)', 'LLANǪUIHUE', '2C.A. 15M³', 'INDUSTRIALES', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ALVI SUPERMERCADO MAYORISTA S.A.', 'PUERTO MONTT', '3 LUTOCAR 1.100LTS-RECOLE', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ALVI SUPERMERCADO MAYORISTA S.A.', 'LA UNION', 'N/A RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ALVI SUPERMERCADO MAYORISTA S.A.', 'VALDIVIA', '1 C.C. 15M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('AǪUAGESTION S.A.', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ARARAT SPA OBRA DEJANDO HUELLA-OJOS DEL CALBUCO', 'PUERTO MONTT/ALERCE', '2C.A. 15M³', 'ESCOMBROS', 'ESCOMBRERA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ARIZTIA COMERCIAL LTDA', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ASTILLEROS PANITAO SPA ASTILLERO', 'PUERTO MONTT', '1 C.A. 15M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ASTILLEROS PANITAO SPA ASTILLERO', 'PUERTO MONTT', '1 C.A. 20M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ASTILLEROS PANITAO SPA WALBUSCH', 'PUERTO MONTT', '1C.A. 15M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('AUTOMOTRIZ SALFA SUR LTDA', 'PUERTO MONTT', '1 C. METALICO 4,5M³-FURGO', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('BLAUWAL SPA', 'CHILOE', '1C.A. 15M³', 'ESCOMBROS', 'ESCOMBRERA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('CARNES ÑUBLE', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('CARTULINAS CMPC SPA', 'VALDIVIA', '1C.A.15M³- 1 C.C 15M³', 'VARIOS', 'VALDIVIA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('CBB CEMENTOS - READY MIX LIMITADA', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('CECINAS BRAUNAU SPA', 'PUERTO MONTT', '8 LUTOCAR DE 1,100LTS.-REC', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('CLIFFS INVERSIONES CHILE LIMITADA', 'LOS MUERMOS', '2 LUTOCAR DE 1,100LTS-REC', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('CNA CHILE SPA', 'PUERTO MONTT', '1 C.A. 20M³', 'ASIMILABLE', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('COOPERATIVA AGRICOLA Y LECHERA LA UNION COLUN', 'LA UNION', 'N/A ATMOSFERICO', 'LODOS', 'HIDRONOR-GENERA 4');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('COMERCIAL AMAR Y HERMANOS Y CIA LTDA', 'LLANǪUIHUE', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('COMERCIAL AMAR Y HERMANOS Y CIA LTDA', 'LLANǪUIHUE', 'FURGON', 'CARTON', 'SOREPA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('COMERCIAL AUTONAUTICA LTDA.', 'PUERTO MONTT', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('COMERCIAL E INM. DEL SUR', 'PUERTO MONTT', '1C.A. 15M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('COMERCIAL RTI SPA', 'PUERTO MONTT', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('COMERCIAL RTI SPA', 'PUERTO VARAS', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('CONFECCIONES LEYAD LTDA.', 'PUERTO MONTT', '2C.A.15M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('CONPAX VALKO ARRIGONI (EMPALME)', 'PUERTO MONTT', '1 C.A. 15M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('CONSORCIO PUENTE CHACAO S.A CHACAO 20M³', 'CHACAO', '1 C.A. 20M³', 'ASIMILABLE', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('CONSORCIO PUENTE CHACAO S.A PARGUA 15M³', 'PARGUA', '1 C.C.15M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('CONSORCIO PUENTE CHACAO S.A PARGUA 20M³', 'PARGUA', '1 C.A. 20M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('CONSTRUCCIONES Y SERVICIOS CONSSEG LTDA.', 'PUERTO MONTT', '1 C.A. 15M³', 'ESCOMBROS', 'ESCOMBRERA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('CONSTRUCTORA BAǪUEDANO SUR LTDA. ALTOS DE TENGLO', 'PUERTO MONTT', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('CONSTRUCTORA NOTROS', 'PUERTO MONTT', '1 C.A. 15M³', 'ESCOMBROS', 'ESCOMBRERA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('CONSTRUCTORA WPF Y CIA LTDA', 'PUERTO MONTT', '1 C.C.15M³', 'ESCOMBROS', 'ESCOMBRERA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('COOP.DE SERV.SANITARIOS CARELM', 'CARELMAPU', '1 C.C. LODO 15M³', 'LODOS', 'ECOPRIAL');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('COOPERATIVA CAMPOS AUSTRALES', 'LLANǪUIHUE', '1 C.C. LODO 15M³', 'BARRIDO DE CALLE', 'ESCOMBRERA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('COOPERATIVA CAMPOS AUSTRALES', 'LLANǪUIHUE', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('CORPORACION EDUCACIONAL RALUN', 'PUERTO MONTT', 'N/A-FURGON', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('DANISCO CHILE S.A.', 'PARGUA 15m³', 'N/A ATMOSFERICO', 'LODOS', 'ECOPRIAL');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('DANISCO CHILE S.A.', 'PARGUA 20m³', 'N/A ATMOSFERICO', 'LODOS', 'ECOPRIAL');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('DANISCO CHILE S.A.', 'PARGUA 30m³', 'N/A ATMOSFERICO', 'LODOS', 'ECOPRIAL');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('DETROIT S.A. EWOS', 'PUERTO MONTT', '1 C.A. 20M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('DETROIT S.A.ASTLLEROS', 'PUERTO MONTT', '2 C.A. 20M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('DLC SOLUCIONES EN PACKAGING SPA', 'PUERTO MONTT', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('DISTRIBUIDORA CUMMINS CHILE S.A.', 'PUERTO MONTT', '1 LUTOCAR 110LTS-RECOLEC', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('EMPRESA AǪUACHILE S.A. CARDONAL', 'PUERTO MONTT', '1 C.A. 30M³- ENFARDADORA', 'PLASTICO', 'SUR RECICLAJE');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('EPYSA BUSES LTDA', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ESMAX RED LIMITADA OSORNO', 'OSORNO', 'N/A-RECOLECTOR', 'ASIMILABLE', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ESMAX RED LIMITADA PUYEHUE', 'PEYEHUE', 'N/A-RECOLECTOR', 'ASIMILABLE', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ESMAX RED LIMITADA PTO. MONTT-PTO. VARAS-TRAPEN', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('FEDIR CHILE SPA', 'VALDIVIA', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLE', 'MORROMPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('FERRETERIAS WEITZLER S.A. PTO VARAS-PTO MONTT-JJMIRA-URMENETA', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('FORMADORA DE ACEROS DEL SUR S.A.', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('FRANCISCA ROJAS VALIN CENTRO DE VIDA ASI', 'VALDIVIA', 'N/A-RECOLECTOR', 'ASIMILABLE', 'MORROMPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('FRIGORIFICO DE OSORNO S.A', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('FRIGORIFICOS MASCATO S. A.', 'PUERTO MONTT', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('FRIOPACK SPA', 'PUERTO MONTT', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('FRYS LTDA.', 'PUERTO MONTT', '1 C.A. 15M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('FUNDACION CHINǪUIHUE', 'PUERTO MONTT', '1 C.A. 15M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('FUNDACION CHINǪUIHUE', 'PUERTO MONTT', 'N/A RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('GRANJA MARINA TORNAGALEONES S.A.', 'ǪUELLON', 'N/A ATMOSFERICO', 'LODOS', 'ECOPRIAL');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('GRIPSHIP SPA', 'PUERTO MONTT', 'N/A TOLVA ESPORADICA', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('HECTOR ELISEO BAZA MELLA', 'PUERTO MONTT', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('HOSPITAL PUERTO MONTT SERVICIO DE SALUD', 'PUERTO MONTT', 'N/A ATMOSFERICO', 'LODOS', 'ECOPRIAL');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('HOTEL MANǪUEHUE PUERTO MONTT SPA', 'PUERTO MONTT', 'N/A-FURGON', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('INMOBILIARIA POWER CENTER S.A. PALOMA Y CARDONAL', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('INMOBILIARIA POWER CENTER S.A. ROTONDA Y PASEO DEL MAR', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('INMOBILIARIA POWER CENTER S.A. AMPLIACION COSTANERA', 'PUERTO MONTT', '1 C.C 15M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('INMOBILIARIA POWER CENTER S.A. MALL COSTANERA', 'PUERTO MONTT', '1 COMPACTADOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('INMOBILIARIA POWER CENTER S.A. MALL PASEO ALERCE', 'PUERTO MONTT', '1 COMPACTADOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('INMOBILIARIA POWER CENTER S.A. MALL PASEO PTO VARAS', 'PUERTO VARAS', '1 COMPACTADOR', 'ASIMILABLE', 'LA LAJA/AUN POR IMPLEMENTAR');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('IDEAL S.A.', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ILUSTRE MUNICIPALIDAD DE LANCO', 'LANCO', 'N/A ATMOSFERICO', 'LODOS', 'ECOPRIAL');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('ILUSTRE MUNICIPALIDAD DE PUERTO MONTT', 'PUERTO MONTT', 'N/A SOLO DISPOSICION', 'ESCOMBROS', 'ESCOMBRERA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('IMPLEMENTOS S.A.', 'PUERTO MONTT', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('IMPERIAL S.A', 'PUERTO MONTT', '1 C,A 20M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('INGENIERIA Y MAESTRANZA SOLDASUR LIMITAD', 'PUERTO MONTT', NULL, 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('INMOBILIARIA HERKAS LIMITADA', 'PUERTO MONTT', NULL, 'ESCOMBROS', 'ESCOMBRERA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('INVERSIONES EL ARRIERO S.A', 'PUERTO MONTT', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('INVERSIONES ENEX S.A 924', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('INVERSIONES ENEX S.A 379', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('INVERSIONES LITORAL SPA.', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('KAUFMANN S.A VEHICULOS MOTORIZADOS LLANǪUIHUE', 'LLANǪUIHUE', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('KAUFMANN S.A VEHICULOS MOTORIZADOS LLANǪUIHUE', 'LLANǪUIHUE', 'VALORIZACION', 'VALORIZABLES', 'VALORIZACIÓN');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('KAUFMANN S.A VEHICULOS MOTORIZADOS OSORNO', 'OSORNO', 'N/A-RECOLECTOR', 'ASIMILABLE', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('KAUFMANN S.A VEHICULOS MOTORIZADOS OSORNO', 'OSORNO', 'VALORIZACION', 'VALORIZABLES', 'VALORIZACIÓN');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('KAWESHKAR SPA', 'PUERTO MONTT', '1 C.C.15M³', 'LODOS', 'ECOPRIAL');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('KAWESHKAR SPA', 'PUERTO MONTT', '1 C.A.15M³', 'CONCHILLA', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('KOMATSU CHILE S.A.', 'PUERTO MONTT', '1 LUTOCAR 110LTS-RECOLEC', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('LOGISTICA TEPUAL LTDA (DIMARINE)', 'PUERTO MONTT', '1 COMPACTADOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('LOGISTICA TEPUAL LTDA (DIMARINE)', 'PUERTO MONTT', 'N/A VALORIZACIÓN', 'VALORIZABLES', 'VALORIZACIÓN');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('METAL CONSTRUCTORA MCA', 'PUERTO MONTT', '1 C.A. 20M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('MAǪUINARIAS SUR S.A.', 'PUERTO MONTT', '2 C.METALICOS 4,5M³-RECOL', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('MAǪUINARIAS TORRES & WHITE SPA', 'PUERTO MONTT', NULL, 'SOLO DISPOSICION', 'ESCOMBRERA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('MELON S.A.', 'PUERTO MONTT', '1 C.C.15M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('MELON S.A.', 'PUERTO MONTT', 'N/A RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('MELON S.A.', 'PUERTO MONTT', 'N/A VALORIZACIÓN', 'VALORIZABLES', 'VALORIZACIÓN');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('MOP DIRECCION GENERAL DE OBRAS PUBLICAS', 'PUERTO MONTT', '1 C.A. 15M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('NEWREST COMPASS CATERING Y SERVICIOS CHILE LTDA.', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('OTERO Y DOMINGUEZ LTDA.', 'PUERTO MONTT', '2 C.METALICOS 4,5M³-RECOL', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('OVANBAL S.A.', 'PUERTO MONTT', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('OXIǪUIM S.A.', 'PUERTO MONTT', '1 C.C. 15M³', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('PATAGONIA BIOTECNOLOGIA SPA', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('PATAGONIA REDES', 'PUERTO MONTT', '1 C.A. 20M³', 'INDUSTRIALES', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('PENA SPOERER Y CIA S.A', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('PERROT SPA', 'PUERTO MONTT', '3 C.METALICOS 4,5M³-RECOL', 'ASMILABLES - VALORIZABLES', 'LA LAJA- VALORIZACIÓN');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('PRECON S.A', 'VALDIVIA', '1 C.A. 15M³', 'ESCOMBROS', 'ESCOMBRERA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('PRECON S.A', 'VALDIVIA', '1 C.C. 15M³', 'ASIMILABLES', 'MORROMPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('PROCESADORA CALBUCO SPA VALORIZABLES', 'CALBUCO', '1 C.A 30M³-1 C.C. 30M³- ENFA', 'VALORIZABLES', 'VALORIZACIÓN');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('PROCESADORA DE PLASTICO PUELCHE LTDA', 'PUERTO MONTT', '2 LUTOCAR DE 1,100LTS-REC', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('PROCESADORA MAR DEL SUR SPA.', 'CHONCHI', 'N/A ATMOSFERICO', 'LODOS', 'ECOPRIAL');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('PROCESADORA MAR DEL SUR SPA.', 'CHONCHI', '1 C.C. 30M³', 'CARTÓN', 'SOREPA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('PROCESADORA MAR DEL SUR SPA.', 'CHONCHI', '1 C.C. 30M³', 'PLASTICOS', 'SUR RECICLAJE');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('PRODALAM S.A.', 'PUERTO MONTT', 'N/A RECOLECTOR', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('PRODALAM S.A.', 'VALDIVIA', '1 C.A. 15M³', 'ASIMILABLES', 'MORROMPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('PRODUCTOS FERNANDEZ S.A.', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('PUERTO PUNTA CAULLAHUAPI S.A.', 'PUERTO MONTT', '1 C.A. 20M³', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('PUGA, MUJICA ASOCIADOS S.A.', 'PUERTO MONTT', '2C.A. 15M³', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('REDES Y NETS LTDA.', 'PUERTO MONTT', '1 C.A. 15M³', 'CONCHILLA', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('RENDIC HERMANOS S.A. ALERCE I-ALERCE II, ROTONDA, CALBUCO II', 'PUERTO MONTT', 'N/A RECOLECTOR', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('RENDIC HERMANOS S.A. ARAUCO VALDIVIA', 'VALDIVIA', '1 COMPACTADOR', 'ASIMILABLES', 'MORROMPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('RENDIC HERMANOS S.A. CALBUCO I', 'PUERTO MONTT', '1 COMPACTADOR', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('RENDIC HERMANOS S.A. COYHAIǪUE', 'COYHAIǪUE', '1 COMPACTADOR', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('RENDIC HERMANOS S.A. DALCAHUE, CHONCHI, ANCUD', 'CHILOE', '3 COMPACTADOR', 'ASIMILABLES', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('RENDIC HERMANOS S.A. LAS ANIMAS, LA UNION', 'VALDIVIA', 'N/A-RECOLECTOR', 'ASIMILABLES', 'MORROMPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('RENDIC HERMANOS S.A. LLANǪUIHUE', 'PUERTO MONTT', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('RENDIC HERMANOS S.A. LOS MUERMOS, LOS VOLCANES, EL TEPUAL, MANFRE', 'PUERTO MONTT', 'N/A RECOLECTOR', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('RENDIC HERMANOS S.A. LOS NOTROS', 'PUERTO MONTT', '1 COMPACTADOR', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('RENDIC HERMANOS S.A. MIRASOL', 'PUERTO MONTT', '7 CONT. PLASTICOS DE 360LT', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('RENDIC HERMANOS S.A. OSORNO CENTRAL, OSORNO ORIENTE', 'OSORNO', '2 COMPACTADOR', 'ASIMILABLES', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('RENDIC HERMANOS S.A. ǪUELLON I, ǪUELLON II', 'ǪUELLON', '2 COMPACTADOR', 'ASIMILABLES', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('RENDIC HERMANOS S.A. URMENETA', 'PUERTO MONTT', '12 CONT. PLASTICOS DE 240L', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('RENTOKIL INITIAL CHILE SPA', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('RESISALUD S.A.', 'PUERTO MONTT', '1 LUTOCAR-RECOLECTOR', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('RHONA S.A.', 'PUERTO MONTT', '2 C.METALICOS 4,5M³-RECOL', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('RIO LARǪUI LTDA', 'PUERTO MONTT', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SALINAS Y FABRES S.A.', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SALINAS Y FABRES S.A.', 'PUERTO VARAS', 'N/A-RECOLECTOR', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SALMONES AYSEN S.A. CANELOS', 'VARIOS', '3 C.C.15M³', 'ASIMILABLES', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SALMONES AYSEN S.A. HALCONES,', 'VARIOS', '3 C.C.15M³', 'ASIMILABLES', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SALMONES AYSEN S.A. NILAHUE', 'VARIOS', '3 C.C.15M³', 'ASIMILABLES', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SALMONES AYSEN S.A.ROLLIZO', 'ROLLIZO', '1 C.C.15M³', 'ASIMILABLES', 'REMAP');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SALMONES CAMANCHACA S.A.', 'PUERTO MONTT', '1 COMPACTADOR', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SALMONES CAMANCHACA S.A.', 'PUERTO MONTT', '1 C.A.30M³', 'INDUSTRIALES', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SALMONES CAMANCHACA S.A.', 'CALBUCO', '1 COMPACTADOR/2 C.A. 15Y2', 'ASIMILABLES/INDUSTRIAL', 'LA LAJA/REMAP');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SALMONES CAMANCHACA S.A.', 'PETROHUE', '1 COMPACTADOR/1C.A.15M³', 'ASIMILABLES/INDUSTRIAL', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SALMONES CAMANCHACA S.A.', 'PETROHUE', '1 C.A.15M³', 'INDUSTRIALES', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SALMONET S.A.', 'CHONCHI', 'N/A ATMOSFERICO', 'LODOS', 'RILESUR');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SALUDABLE SPA', 'PUERTO MONTT', '1 C.C.15M³', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SAMEX SPA', 'PUERTO MONTT', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SEALAND ACUACULTURE S.A.', 'LAGO RANCO VALDIVIA', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLES', 'MORROMPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SOC. FAENADORA Y COMER. DE CARNES ABASC', 'PUERTO MONTT', '3. C.C LODOS 15M³', 'CARNICOS', 'HIDRONOR');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SOC. ADL DIAGNOSTIC CHILE SPA.', 'PUERTO MONTT', 'N/A FURGON', 'DECOMISO', 'REXIN');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SOC. CONCESIONARIA DE LOS LAGOS S.A', 'TOTORAL', '1 C.C.15M³', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SOC. CONCESIONARIA RUTA DEL CANAL S.A.', 'CAMINO PARGUA', '1 C,A 20M³', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SOC. CONCESIONARIA RUTA DEL CANAL', 'PARGUA', '1 C.A 20M³', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SOC. DE TRANSP. ALIRO MUNDACA LTDA.', 'PUERTO MONTT', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SOC. INDUSTRIAL DE PLASTICO LTDA', 'PUERTO MONTT', '1 C. METALICO 4,5M³-RECOLE', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SOC. INMOBILIARIA HURTADO LTDA.', 'PUERTO MONTT', '1 C.A. 15M³', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SOC. PORTUARIA PANITAO S.A.', 'PUERTO MONTT', '3 C.A. 20M³', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SOCIEDAD CLINICA DEL VALLE (CLINICA CHINǪUIHUE)', 'PUERTO MONTT', 'N/A-RECOLECTOR', 'ASIMILABLE', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SOCIEDAD COMERCIAL Y TRANSPORTES CP SPA', 'PUERTO MONTT', '2 LUTOCAR DE 1,100LTS.', 'ASIMILABLES/VALORIZABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SOCIEDAD GASTRONOMICA PA MAR ADENTRO SPA', 'PUERTO MONTT', 'N/A RECOLECTOR', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SOCIEDAD GASTRONOMICA EL SARTEN (LA OLLA)', 'PUERTO VARAS', 'N/A RECOLECTOR', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SOCIEDAD PESCADORES S.A.', 'CALBUCO', '1 C.A 15M³', 'INDUSTRIALES', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SUB SECRETARIA DE SALUD PUBLICA', 'PUERTO MONTT', 'N/A FURGON', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SUB SECRETARIA DE SALUD PUBLICA', 'CASTRO', 'N/A FURGON', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SUB SECRETARIA DE SALUD PUBLICA', 'ǪUELLON', 'N/A FURGON', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SUPER 10 S.A. PUERTO MONTT', 'PUERTO MONTT', 'N/A RECOLECTOR', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SUPERMERCADO CENTRAL (CUGAT)', 'PUERTO MONTT', 'N/A RECOLECTOR', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('SURALIS S.A.', 'VARIOS', 'PRIMARIOS/ BIOSOLIDOS', 'VARIOS', 'PREDIOS/ECOPRIAL');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('TECNO TRUSS', 'PUERTO MONTT', '2 C.A. 20M³', 'INDUSTRIALES', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('TRANSPORTES CRUZ DEL SUR LTDA. MAGALLANES', 'PUERTO MONTT', '1 C.METALICOS 4,5M³ RECOL', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('TRANSPORTES CRUZ DEL SUR LTDA. PILPILCO', 'PUERTO MONTT', '1 C.METALICOS 4,5M³ RECOL', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('TRANSPORTES MARITIMOS TRANSMARǪUIN S.A.', 'PUERTO MONTT', '1 C.A. 20M³', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('TRANSPORTES USANT SPA', 'PUERTO MONTT', 'SOLO DISPOSICION', 'ESCOMBROS', 'ESCOMBRERA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('UNIVERSIDAD SAN SEBASTIAN', 'PUERTO MONTT', '1 COMPACTADOR', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('UNIVERSIDAD SAN SEBASTIAN', 'PUERTO MONTT', '1 C.A. 15M³', 'ESCOMBROS', 'ESCOMBRERA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('VITAPRO CHILE S.A CASTRO', 'CASTRO', '2 COMPACTADORES', 'ASIMILABLES', 'COLLIPULLI');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('VITAPRO CHILE S.A PUERTO MONTT', 'ǪUILLAIPE', '1 C.A. 15M³', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('WALMART CHILE MAYORISTA LTDA.', 'PUERTO MONTT', '1 C.C.15M³', 'ASIMILABLES', 'LA LAJA');
INSERT INTO public.clientes (nombre, ciudad, tipo_contenedor, residuo, disposicion_final) VALUES ('WALMART CHILE MAYORISTA LTDA.', 'OSORNO', '1 C.C.15M³', 'ASIMILABLES', 'COLLIPULLI');